docker run -it -d \
  --label traefik.http.routers.mwandetelefinance.rule=Host\(\`mwandetelefinance.loan-pocket.com\`\) \
  --label traefik.http.routers.mwandetelefinance.tls.certresolver=lets-encrypt \
  --label traefik.http.routers.mwandetelefinance.tls=true \
  --label traefik.http.routers.mwandetelefinance.service=mwandetelefinance-credit-http \
  --label traefik.http.services.mwandetelefinance-credit-http.loadbalancer.server.port=80 \
  --name mwandetelefinance \
  --network web \
  --restart always \
  --expose 80 \
  emasanga/mikoposoft:may13